#!/bin/bash
### BEGIN INIT INFO
# Provides:          example
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: example script
# Description:       This script is an example LSB init
#                    script.
### END INIT INFO

__IP=/sbin/ip

function do_start() {
        echo -n "Ajout des routes vers le réseau VMs. Code retour: "
        $__IP route add 194.199.228.0/23 dev vmbr1 scope link &> /dev/null
        RET=$?
        echo $RET
        return $RET
}

function do_stop() {
        echo -n "Suppression des routes vers le réseau VMs. Code retour: "
        $__IP route del 194.199.228.0/23 dev vmbr1 &> /dev/null
        RET=$?
        echo $RET
        return $RET
}

function do_restart() {
    do_stop
    do_start
    exit $?
}

function show_usage() {
        echo "#########################################"
        echo "# Routes vers 194.199.228.0/23"
        echo "#########################################"
        echo "Utilisation: $0 start|stop|restart"
        echo ""
}

case $1 in
    start)
        do_start
        exit $?
        ;;
    stop)
        do_stop
        exit $?
        ;;
    restart)
        do_restart
        exit $?
        ;;
    status)
        # simple affichage de la table de routage
        $__IP r
        ;;
    *)
        show_usage
        exit 1
        ;;
esac
